/**
 * JC logo badge: a Group centred on the origin, two units wide, holding the extruded
 * letterforms and the accent chevron as separately coloured meshes.
 *
 * The profile point arrays, extrude depths, pivot offsets and material scalars below are
 * taken verbatim from docs/3d/jc-logo/createJcLogoModel.ts, generated by the img2threejs
 * pipeline from src/assets/jclogoblack.png. Only the model path is ported: the generated
 * look-dev lights, environment, composer, orbit controls and procedural texture helpers
 * are unused by the site and deliberately left in the archive. Both materials are declared
 * textureless in the spec, so no maps are built here either.
 *
 * Colours are the only parameters, so the badge can follow the site theme.
 */
import * as THREE from 'three';

const INK = '#0a0a0c';
const CHEVRON = '#e08a00';

// "letters", spec component id letters: single closed outline, counters cut by hairline slits.
const LETTERS_PROFILE = {
  depth: 0.12,
  pivotZ: -0.06,
  points: [
    [-0.6507, 0.5], [-0.2297, 0.5], [-0.2249, 0.1842], [-0.2057, 0.1842], [-0.2057, 0.5],
    [-0.1627, 0.5], [-0.1627, 0.323], [-0.1435, 0.323], [-0.1435, 0.5], [0.0144, 0.5],
    [0.0144, 0.433], [0, 0.4282], [-0.0526, 0.3708], [-0.0813, 0.2847], [-0.0813, -0.2847],
    [-0.0526, -0.3708], [0, -0.4282], [0.0144, -0.433], [0.0096, -0.4282], [-0.0287, -0.39],
    [-0.067, -0.3038], [-0.067, 0.3038], [-0.0574, 0.3373], [-0.0287, 0.39], [0.0383, 0.4474],
    [0.1435, 0.4856], [0.2632, 0.5], [0.4211, 0.4904], [0.5072, 0.4665], [0.555, 0.4426],
    [0.622, 0.3804], [0.6555, 0.2895], [0.6555, 0.1651], [0.5359, 0.1651], [0.5359, 0.2703],
    [0.5215, 0.2703], [0.5215, 0.1651], [0.4258, 0.1651], [0.4258, 0.2751], [0.4115, 0.3182],
    [0.3923, 0.3373], [0.3397, 0.3565], [0.2584, 0.3565], [0.2153, 0.3421], [0.1818, 0.3086],
    [0.177, -0.2943], [0.1962, -0.3278], [0.2297, -0.3469], [0.2727, -0.3565], [0.3301, -0.3565],
    [0.3971, -0.3325], [0.4163, -0.3086], [0.4258, -0.2751], [0.4258, -0.1651], [0.5215, -0.1651],
    [0.5215, -0.2847], [0.5359, -0.2847], [0.5359, -0.1651], [0.6555, -0.1651], [0.6555, -0.2895],
    [0.622, -0.3804], [0.5694, -0.433], [0.5072, -0.4665], [0.3876, -0.4952], [0.201, -0.4952],
    [0.067, -0.4617], [0.0096, -0.4282], [0.0144, -0.433], [0.0144, -0.4952], [-0.1435, -0.4952],
    [-0.1435, -0.1746], [-0.1627, -0.1746], [-0.1627, -0.4952], [-0.6555, -0.4952],
    [-0.6555, -0.1651], [-0.4258, -0.1651], [-0.4258, -0.3134], [-0.4163, -0.3325],
    [-0.3971, -0.3517], [-0.3589, -0.3565], [-0.3397, -0.3469], [-0.311, -0.3086], [-0.311, 0.3134],
    [-0.3493, 0.3565], [-0.3923, 0.3565], [-0.4115, 0.3421], [-0.4258, 0.3134], [-0.4258, 0.1651],
    [-0.6555, 0.1651]
  ],
};

// "chevron", spec component id chevron: the accent band, extruded proud of the letter face.
const CHEVRON_PROFILE = {
  depth: 0.05,
  pivotZ: 0.055,
  points: [
    [-0.6459, -0.0072], [-0.6077, -0.0072], [-0.6077, -0.012], [-0.5885, -0.012],
    [-0.5502, -0.0311], [-0.5311, -0.0311], [-0.5215, -0.0215], [-0.4737, -0.012],
    [-0.4737, -0.0072], [-0.4354, -0.0072], [-0.4258, -0.0311], [-0.4306, -0.0311],
    [-0.4354, -0.055], [-0.445, -0.055], [-0.488, -0.0981], [-0.4976, -0.0981], [-0.5359, -0.1364],
    [-0.5455, -0.1364], [-0.5789, -0.1029], [-0.5885, -0.1029], [-0.6029, -0.0837],
    [-0.6124, -0.0837], [-0.6316, -0.0598], [-0.6459, -0.055], [-0.6555, -0.0359],
    [-0.6555, -0.0167]
  ],
};

// Measured material scalars from the spec. Everything the generator left at a neutral
// default is omitted; envMapIntensity 0.8 is the one non-default three.js value.
const LETTERS_MATERIAL = { roughness: { base: 0.62 }, metalness: { base: 0 } };
const CHEVRON_MATERIAL = { roughness: { base: 0.5 }, metalness: { base: 0 } };

// bevelEnabled defaults to true on THREE.ExtrudeGeometry and rounds every corner, which
// would soften the logo's sharp stems and chevron point, so it stays off.
function buildExtrudeShape(points) {
  const shape = new THREE.Shape();
  if (points.length > 0) {
    shape.moveTo(points[0][0], points[0][1]);
    for (let i = 1; i < points.length; i += 1) {
      shape.lineTo(points[i][0], points[i][1]);
    }
  }
  return shape;
}

function buildExtrudeGeometry(profile) {
  return new THREE.ExtrudeGeometry(buildExtrudeShape(profile.points), {
    depth: profile.depth,
    bevelEnabled: false,
    steps: 1,
  });
}

function readLayerNumber(value, keys, fallback) {
  if (typeof value === 'number') return value;
  if (value && typeof value === 'object') {
    for (const key of keys) {
      if (typeof value[key] === 'number') return value[key];
    }
  }
  return fallback;
}

function clamp01(value) {
  return Math.max(0, Math.min(1, value));
}

function clampPbrF0(value) {
  return Math.max(0.02, Math.min(1, value));
}

function clampPbrIor(value) {
  return Math.max(1, Math.min(2.5, value));
}

function clampPbrMetalness(value) {
  return value >= 0.5 ? 1 : 0;
}

function createSculptMaterial(color, spec) {
  // setStyle with an explicit SRGBColorSpace, NOT the numeric constructor: an authored hex
  // is sRGB while THREE.Color(r, g, b) reads linear working-space components, and skipping
  // the transfer function lifts every dark albedo (#0a0a0c would render as a mid grey).
  const material = new THREE.MeshPhysicalMaterial({
    color: new THREE.Color().setStyle(color, THREE.SRGBColorSpace),
    roughness: clamp01(readLayerNumber(spec.roughness, ['base'], 0.76)),
    metalness: clampPbrMetalness(readLayerNumber(spec.metalness, ['base'], 0)),
    ior: clampPbrIor(readLayerNumber(spec.ior, ['base', 'value'], 1.5)),
    specularIntensity: clampPbrF0(readLayerNumber(spec.specularF0, ['base', 'value'], 1)),
    side: THREE.FrontSide,
  });
  material.envMapIntensity = readLayerNumber(spec, ['envMapIntensity'], 0.8);
  return material;
}

function buildPart(name, profile, color, spec) {
  const pivot = new THREE.Group();
  pivot.name = `${name}__pivot`;
  pivot.position.set(0, 0, profile.pivotZ);

  const mesh = new THREE.Mesh(buildExtrudeGeometry(profile), createSculptMaterial(color, spec));
  mesh.name = name;
  pivot.add(mesh);
  return pivot;
}

// Centre the whole badge on the origin and scale it to two units wide, so callers can frame
// it without knowing the source pixel dimensions. The geometries move rather than the pivots,
// which leaves root.position free for the caller.
function normalise(root) {
  const box = new THREE.Box3().setFromObject(root);
  const size = box.getSize(new THREE.Vector3());
  const centre = box.getCenter(new THREE.Vector3());
  root.traverse((object) => {
    if (object.isMesh) object.geometry.translate(-centre.x, -centre.y, -centre.z);
  });
  root.scale.setScalar(2 / size.x);
}

/**
 * Build the JC logo badge.
 *
 * @param {{ ink?: string, chevron?: string }} [colors] CSS hex colours for the letterforms
 *   and the accent chevron.
 * @returns {THREE.Group} A group centred at the origin, about 2 units wide, containing
 *   meshes named "letters" and "chevron", each with its own material.
 */
export function createJcLogoModel({ ink = INK, chevron = CHEVRON } = {}) {
  const root = new THREE.Group();
  root.name = 'JcLogo';
  root.add(buildPart('letters', LETTERS_PROFILE, ink, LETTERS_MATERIAL));
  root.add(buildPart('chevron', CHEVRON_PROFILE, chevron, CHEVRON_MATERIAL));
  normalise(root);
  return root;
}
